version: '3.7'

services:
  database:
    image: "postgres"
    container_name: "database-container"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=db
    ports:
      - "54320:5432"
    networks:
      local_net:
        aliases:
          - databaseservice

  categoryservice:
    depends_on:
      - database
    build:
      context: ./categoryservice
      dockerfile: ./Dockerfile
    ports:
      - "8002:8002"
    networks:
      local_net:
        aliases:
          - categoryservice

  productservice:
    depends_on:
      - database
    build:
      context: ./productservice
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
    networks:
      local_net:
        aliases:
          - productservice

  userservice:
    depends_on:
      - database
    build:
      context: ./userservice
      dockerfile: ./Dockerfile
    ports:
      - "8003:8003"
    networks:
      local_net:
        aliases:
          - userservice

  contentservice:
    depends_on:
      - productservice
      - categoryservice
    build:
      context: ./contentservice
      dockerfile: ./Dockerfile
    ports:
      - "8004:8004"
    networks:
      local_net:
        aliases:
          - contentservice
networks:
  local_net:
    driver: bridge