server:
  port: 8002
spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:54320/db
    username: admin
    password: password1234


