server:
  port: 8002
spring:
  application:
    name: category-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://database:5432/db
    username: admin
    password: password1234


