server:
  port: 8766
spring:
  application:
    name: category-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:54320/db
    username: admin
    password: password1234


